// File generated by Antigravity using Firebase MCP credentials.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Fallback to iOS/macOS config
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWxBcW3Zeh7GT-gJoq92a37Dv7H7R9qRg',
    appId: '1:851630762779:web:463997e476de1dc67c81be',
    messagingSenderId: '851630762779',
    projectId: 'rexharge-7a902',
    authDomain: 'rexharge-7a902.firebaseapp.com',
    storageBucket: 'rexharge-7a902.firebasestorage.app',
    measurementId: 'G-JKTEN6WYLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdf_8a1Tiv2uJuNFtXEbTzm-mfU9GB2w',
    appId: '1:851630762779:android:3008b2998928094a7c81be',
    messagingSenderId: '851630762779',
    projectId: 'rexharge-7a902',
    storageBucket: 'rexharge-7a902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92bYWpR7Ej1XO_4NWj-bMpabRc_YUTNc',
    appId: '1:851630762779:ios:3e28b296bcca80c57c81be',
    messagingSenderId: '851630762779',
    projectId: 'rexharge-7a902',
    storageBucket: 'rexharge-7a902.firebasestorage.app',
    iosBundleId: 'com.example.rexharge',
  );
}
